"""auto-vote

Revision ID: 1715271fff0a
Revises: 41ff1ddab714
Create Date: 2022-09-19 21:45:17.539751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1715271fff0a'
down_revision = '41ff1ddab714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votesORM',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['postsORM.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['usersORM.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votesORM')
    # ### end Alembic commands ###
